# Generated by Django 4.2.7 on 2023-11-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='lang1_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='lang2_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='path1_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='path2_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='path3_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='path4_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='path5_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='title_ru',
        ),
    ]
