# Generated by Django 4.2.7 on 2023-11-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_header_title_en_remove_header_title_hy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='', verbose_name='Background')),
                ('title1', models.CharField(max_length=25, verbose_name='Title 1')),
                ('title1_hy', models.CharField(max_length=25, null=True, verbose_name='Title 1')),
                ('title1_en', models.CharField(max_length=25, null=True, verbose_name='Title 1')),
                ('title2', models.CharField(max_length=25, verbose_name='Title 2')),
                ('title2_hy', models.CharField(max_length=25, null=True, verbose_name='Title 2')),
                ('title2_en', models.CharField(max_length=25, null=True, verbose_name='Title 2')),
                ('text', models.TextField(verbose_name='Text')),
                ('text_hy', models.TextField(null=True, verbose_name='Text')),
                ('text_en', models.TextField(null=True, verbose_name='Text')),
                ('button', models.CharField(max_length=30, verbose_name='Button')),
                ('button_hy', models.CharField(max_length=30, null=True, verbose_name='Button')),
                ('button_en', models.CharField(max_length=30, null=True, verbose_name='Button')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
    ]
