# Generated by Django 4.2.7 on 2023-11-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_about2_aboutcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('title_hy', models.CharField(max_length=40, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=40, null=True, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('text_hy', models.TextField(null=True, verbose_name='Text')),
                ('text_en', models.TextField(null=True, verbose_name='Text')),
                ('button', models.CharField(max_length=30, verbose_name='Button')),
                ('button_hy', models.CharField(max_length=30, null=True, verbose_name='Button')),
                ('button_en', models.CharField(max_length=30, null=True, verbose_name='Button')),
            ],
        ),
    ]
