# Generated by Django 4.2.7 on 2023-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_title', models.CharField(max_length=50, verbose_name='General Title')),
                ('general_title_hy', models.CharField(max_length=50, null=True, verbose_name='General Title')),
                ('general_title_en', models.CharField(max_length=50, null=True, verbose_name='General Title')),
                ('general_subtitle', models.CharField(max_length=100, verbose_name='General Subtitle')),
                ('general_subtitle_hy', models.CharField(max_length=100, null=True, verbose_name='General Subtitle')),
                ('general_subtitle_en', models.CharField(max_length=100, null=True, verbose_name='General Subtitle')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('title_hy', models.CharField(max_length=80, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=80, null=True, verbose_name='Title')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('text1_hy', models.TextField(null=True, verbose_name='Text 1')),
                ('text1_en', models.TextField(null=True, verbose_name='Text 1')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('text2_hy', models.TextField(null=True, verbose_name='Text 2')),
                ('text2_en', models.TextField(null=True, verbose_name='Text 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('button', models.CharField(max_length=30, verbose_name='Button')),
                ('button_hy', models.CharField(max_length=30, null=True, verbose_name='Button')),
                ('button_en', models.CharField(max_length=30, null=True, verbose_name='Button')),
            ],
        ),
    ]
