# Generated by Django 4.2.7 on 2023-11-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_questioncontainer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncontainer',
            options={'verbose_name': 'Question Container', 'verbose_name_plural': 'Question Container'},
        ),
        migrations.AlterField(
            model_name='questioncontainer',
            name='general_subtitle',
            field=models.CharField(max_length=150, verbose_name='General Subtitle'),
        ),
        migrations.AlterField(
            model_name='questioncontainer',
            name='general_subtitle_en',
            field=models.CharField(max_length=150, null=True, verbose_name='General Subtitle'),
        ),
        migrations.AlterField(
            model_name='questioncontainer',
            name='general_subtitle_hy',
            field=models.CharField(max_length=150, null=True, verbose_name='General Subtitle'),
        ),
    ]
