# Generated by Django 4.2.7 on 2023-11-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_questioncontainer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60, verbose_name='Question')),
                ('question_hy', models.CharField(max_length=60, null=True, verbose_name='Question')),
                ('question_en', models.CharField(max_length=60, null=True, verbose_name='Question')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('text1_hy', models.TextField(null=True, verbose_name='Text 1')),
                ('text1_en', models.TextField(null=True, verbose_name='Text 1')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('text2_hy', models.TextField(null=True, verbose_name='Text 2')),
                ('text2_en', models.TextField(null=True, verbose_name='Text 2')),
            ],
        ),
    ]
